name: Build iOS IPA on Mac

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: Install MAUI workloads
      run: |
        dotnet workload install maui-ios
        dotnet workload install maui-maccatalyst
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build iOS
      run: dotnet build -c Release -f net8.0-ios
    
    - name: Publish iOS IPA
      run: dotnet publish -c Release -f net8.0-ios -p:RuntimeIdentifier=ios-arm64
    
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: ios-app
        path: bin/Release/net8.0-ios/publish/*.ipa
