name: Build iOS IPA (Unsigned)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build iOS (Debug)
      run: dotnet build -c Debug -f net8.0-ios
    
    - name: Publish iOS (Debug)
      run: dotnet publish -c Debug -f net8.0-ios -p:RuntimeIdentifier=ios-arm64
    
    - name: Upload Debug IPA
      uses: actions/upload-artifact@v3
      with:
        name: ios-app-debug
        path: bin/Debug/net8.0-ios/publish/*.ipa
